### ISSUE TITLE
dates to label

### ISSUE THREAD

**Issue by jasonebox** [jasonebox/SICE_classes#1]
2017-07-12
2020-07-22
2022-07-31

find data in ./SICE_rasters

**Comment by captainjasper** [comment]
Done!

**Comment by jasonebox** [comment]
I removed from 2022-07-31 what I think was one of ~5 areas that was more a cloud shadow than a flooded area

**Comment by jasonebox** [comment]
I removed and re-wrote some 2022-07-31 areas
