### ISSUE TITLE
output RGB image as geotiff

### ISSUE THREAD

**Issue by jasonebox** [jasonebox/SICE_classes#2]
develop SICE_classes_SVC_v2, see temp=RGBx, output to same dir that has the rasters

**Comment by captainjasper** [comment]
Done! I added it to a new version of the code called "SICE_classes_SVC_v2_RGB_test.py" and it seems to work fine. Feel free to test it and add it to the original code. See screenshot below: 
![Screenshot 2023-08-23 124450](https://github.com/jasonebox/SICE_classes/assets/105976693/d6831385-9da4-4eff-9642-f7c6a9e31716)

**Comment by captainjasper** [comment]
Remember to save the RGB raster files manually at a different location, since GitHub can't push files of that size - at least without extensions.

**Comment by jasonebox** [comment]
nice. for smaller file size, did you add lzw compression to the save from rasterio?

**Comment by captainjasper** [comment]
Added compression and it works! Still, RGB files are larger than the recommended limit of 50 MB, but GitHub is able to push them.
